### ISSUE TITLE
GigyaSwift does not compile with Xcode 12 Beta 6

### ISSUE THREAD

**Issue by shivamkapur** [SAP/gigya-swift-sdk#1]
I integrated the gigya core swift framework via cocoapods, 
`pod install` works just fine - however the project does not compile.

It throws an error `Segmentation Fault 11`

<img width="1154" alt="Screenshot 2020-09-08 at 6 53 40 PM" src="https://user-images.githubusercontent.com/34154225/92481957-b2b1a900-f204-11ea-8198-5208dbccb7a9.png">

error logs - 
<unknown>:0: error: unable to execute command: Segmentation fault: 11
<unknown>:0: error: compile command failed due to signal 11 (use -v to see invocation)

Happy to provide more insights if needed.

Thanks,
Shivam

**Comment by sagishm** [comment]
This is a bug in Xcode 12 beta 6.
Link: https://developer.apple.com/documentation/xcode-release-notes/xcode-12-beta-release-notes

`Widgets may crash when built for release. (65862827, 67001496)

Workaround: Set DEAD_CODE_STRIPPING to NO in the extension target’s build settings. When you upload the application to App Store Connect, also unset “Include bitcode for iOS content” in the App Store Connect distribution options.
`
Also, I have seen another issue, sometimes the build is failed and you need to play with the build and clean build project to get success.

**Comment by shivamkapur** [comment]
I see, I tried doing what you just recommended. However, it didn't work on my project. 
I tried clone this very repo and tried compiling it too - it still failed. Would using a static framework help instead?

**Comment by sagishm** [comment]
don't think so, I checked it in my test project and after I change the `DEAD_CODE_STRIPPING` it works.
try to clean the `DerivedData` folder and try again.

**Comment by sagishm** [comment]
Also, the best solution is to wait for the next Xcode release.
if you need it ASAP and only for testing you can go to 'GigyaApiResult.swift' file and change the `LoginApiError` from struct to class.

**Comment by gheerish** [comment]
Thanks, the DEAD_CODE_STRIPPING workaround has worked for me

**Comment by shivamkapur** [comment]
Thanks @sagishm - I was able to make the project run locally. Will wait for the next Xcode version to come out.

**Comment by aruffolo** [comment]
Hi,
Let me know if I should open a separate issue.
The compilation crash occurs still in the latest Xcode 12 GM.
The suggested solution is not working, do you have any other clue?

**Comment by pytel87** [comment]
I am having the same issue with latest Xcode 12. 
Dead code stripping to NO is not working for me.
