### ISSUE TITLE
Gigya incompatible with Xcode 12.2

### ISSUE THREAD

**Issue by RichP** [SAP/gigya-swift-sdk#10]
Need new version of Gigya compiled for Xcode 12.2 now that it has been released by Apple

**Comment by sagishm** [comment]
we will release soon, you can using our `CocoaPods` to get compatibility.

**Comment by RichP** [comment]
We do not use cocoapods.  We use Carthage.   Any chance you could update to also support Carthage?

**Comment by sagishm** [comment]
Carthage is on the roadmap, we will release the fixed version as soon as possible.

**Comment by dominic-plouffe** [comment]
I also need a new version of the Gigya.framework. When do you expect to release it?

**Comment by RichP** [comment]
Any news on when you will release this?

**Comment by sagishm** [comment]
Version 1.1.6 is released with compatibility for Xcode 12.2.
