### ISSUE TITLE
Registration function doesn't return Interruption for Conflicting Email

### ISSUE THREAD

**Issue by illphil610** [SAP/gigya-swift-sdk#11]
I am not receiving an interruption when trying to register a user with the same email address.  Instead I am receiving a 400001 Validation error.  When calling gigya.register and the email doesnt exist, it works just fine and I receive my verification email but when trying to test the use case of a user who is already registered but they try again, we can't catch this interruption as it says in your docs (see below).  We have made a temporary call to the `accounts.isAvailableLoginID` which is working just fine but wanted to see what your thoughts on this are as this is an unnecessary step since your sdk should support this.  

![Screen Shot 2020-11-18 at 9 53 48 PM](https://user-images.githubusercontent.com/20159896/99614944-8f675f00-29e8-11eb-8e3a-bb2cd4013a2b.png)

**Comment by sagishm** [comment]
We currently do not support a specific interruption when registering with a used email address.
When doing so you will receive the described error.
We will look into this in the future.

Thanks you.

**Comment by illphil610** [comment]
I think you need to update your documentation then.... It specifially states the SDK can handle this Interruption. 

![Screen Shot 2020-12-02 at 10 57 55 AM](https://user-images.githubusercontent.com/20159896/100897237-7d2bfd00-348d-11eb-9f35-5404aab23bb8.png)

**Comment by sagishm** [comment]
Basically, the docs are fine.
We discussed on the existing email, you will get `conflictingAccount` when the email exists in another provider.
For example:
- Register with Facebook account -> logout -> register with site but with same email as you regisred in Facebook -> should get `conflicationAccount`.
Also, you need to enable Link account in the Console -> Policies -> Link Accounts Support.

**Comment by illphil610** [comment]
Where does it state that interruption will only be returned when registering via social login providers?

**Comment by sagishm** [comment]
that's not what I said, I just gave an example.
if you need more help please open incident: https://developers.gigya.com/display/GD/Opening+A+Support+Incident

**Comment by illphil610** [comment]
You told me in the first response that this wasn't supported in the SDK then closed the ticket.  I state that your docs show this SHOULD be supported and you tell me "you will get `conflictingAccount` when the email exists in another provider" and then give facebook as an example which is a social provider.  The entire point of this case was to ask why I am not receiving the Interruption that your docs state should be returned.  You tell me first it's not supported and now you tell me it is supported?  What you are saying is not making sense...  I will be opening up a support ticket and will escalate this.  Thanks.

**Comment by sagishm** [comment]
the `gigya.register` method is only for site registration, if you try to register with an existing email (registred by site) you will get an error if you register with a non-exists site account but social exists with the same email you will get a conflicting account.
