### ISSUE TITLE
Social login Server Login Error #500002

### ISSUE THREAD

**Issue by ghena** [SAP/gigya-swift-sdk#12]
Dear sirs, i found a problem during a  social login with google using swift.

We are using this GoogleWrapper (see attachment)
But we have this error:

{ errorCode: 500002,
  errorMessage: 'Server login error',
  oggetto: '{"callId":"71c91fbce0e84c06987dfcf7280af0c5","statusCode":201,"errorCode":500002,"requestData":"ew0KICAiY2FsbElkIjogIjcxYzkxZmJjZTBlODRjMDY5ODdkZmNmNzI4MGFmMGM1IiwNCiAgImVycm9yQ29kZSI6IDUwMDAwMiwNCiAgImVycm9yTWVzc2FnZSI6ICJTZXJ2ZXIgbG9naW4gZXJyb3IiLA0KICAiYXBpVmVyc2lvbiI6IDIsDQogICJzdGF0dXNDb2RlIjogNTAwLA0KICAic3RhdHVzUmVhc29uIjogIkludGVybmFsIFNlcnZlciBFcnJvciIsDQogICJ0aW1lIjogIjIwMjAtMTEtMjJUMTY6MzE6NTguODAwWiIsDQogICJlcnJvckRldGFpbHMiOiAiNTAwMDAyIC0gU2VydmVyIGxvZ2luIGVycm9yIg0KfQ==","errorMessage":"Server login error"}',
  result: false }

We are currently on integration environment.

There is a recent wrapper to use to finalize login with google ?
Regards.

[GoogleWrapper.swift.zip](https://github.com/SAP/gigya-swift-sdk/files/5579821/GoogleWrapper.swift.zip)

**Comment by sagishm** [comment]
Hi,
it's look like implementation issue, when you want to add Google as provider you need to add 2 keys to your plist file:
```
GoogleClientID: <iOS key from google console>
GoogleServerClientID: <Web application key from google console>
```
Make sure you created the both keys in your Google console then go to Gigya console and add the Web application key to Google provider setting.

**Comment by ghena** [comment]
Hi,
thanks for reply.

I have this keys inside info.plist
Without it the login view goes on error.
The application setup is done by another company so I Cant control it.

I ask you if the wrapper seems  is correct or not.
I'm not sure about parameter passed using completionHandler in the delegate method sign.

Please le me know if exist an official wrapper.
Regards.

**Comment by sagishm** [comment]
no, looks like someone modified the file.
You can download the official (tested) wrapper from here: 
https://github.com/SAP/gigya-swift-sdk/releases/tag/core%2Fv1.1.6

**Comment by ghena** [comment]
Ok I'm going to check.
I will update you.
thanks a lot.

**Comment by ghena** [comment]
with the new wrapper it works.
Thanks.
