### ISSUE TITLE
[Google Sign In] 403 disallowed_useragent error on iOS

### ISSUE THREAD

**Issue by jeremie-movify** [SAP/gigya-swift-sdk#14]
Hello,

We have successfully implemented the Gigya Swift SDK in one of our apps.
We currently support 3 providers: Facebook, Apple Sign In (on iOS) and Google Sign In. Both the Facebook and Apple Sign In providers work without issues, but upon trying to authenticate using the GoogleWrapper, we face the following issue:

`Error 403: disallowed_useragent`

After some research, we found this SO post:
https://stackoverflow.com/a/41059043
which seems to indicate that the embedded webView is no more the way to use Google Sign In to authenticate, but that [GTMAppAuth](https://github.com/google/GTMAppAuth) should be used instead.

The GoogleWrapper doesn't use the GTMAppAuth APIs, nor does the sample app (downloaded from https://github.com/SAP/gigya-swift-sdk/releases/tag/core%2Fv1.1.6). Is there some extra configuration needed, or is using GTMAppAuth part of your roadmap ?

Many thanks,

Jérémie

**Comment by jeremie-movify** [comment]
![Uploading IMG_7109.jpg…]()

**Comment by jeremie-movify** [comment]
A bit more info, I'm trying to use Google Sign In on an iOS 14.2 emulator, which user agent is the following:
Mozilla/5.0 (iPhone; CPU iPhone OS 14_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

**Comment by sagishm** [comment]
Hi
Add the following code to your `AppDelegate.swift` then attach the logs here:
`GigyaLogger.setDebugMode(to: true)`

**Comment by jeremie-movify** [comment]
> Hi
> Add the following code to your `AppDelegate.swift` then attach the logs here:
> `GigyaLogger.setDebugMode(to: true)`
> Also, what version of Google sdk you are used ?

Good morning @sagishm ,

We're using version 1.1.6 of the Gigya SDK.

Here are the logs (Gigya initialisation & trying to sign in with the Google provider):

`[NetworkAdapter]: Start: socialize.getSDKConfig
[NetworkProvider]: [Request]:httpBody, jsonData: apikey=[omitted]&format=json&gmid=oNnyVOL4GolwfTl5eeD%2Fnd4BH7Qe92T6G2JFHGQvKfU%3D&httpStatusCodes=false&include=permissions%2Cids%2CappIds&sdk=ios%5Fswift%5F1%2E1%2E6&targetEnv=mobile&ucid=Y6DLea%2F5CpfzKiYzjPFitA%3D%3D&
[SessionService]: [setSession]: failure parsing data
[ApiService]: [Response]: InitSdkResponseModel(ids: Gigya.InitSdkIdsModel(ucid: "Y6DLea/5CpfzKiYzjPFitA==", gmid: "oNnyVOL4GolwfTl5eeD/nd4BH7Qe92T6G2JFHGQvKfU="))
[SocialProvidersManager]: [Google] - use webview
2020-11-30 08:45:57.634323+0100 VRTLoginUI_Example[49948:480596] WF: === Starting WebFilter logging for process VRTLoginUI_Example
2020-11-30 08:45:57.634486+0100 VRTLoginUI_Example[49948:480596] WF: _userSettingsForUser : (null)
2020-11-30 08:45:57.634604+0100 VRTLoginUI_Example[49948:480596] WF: _WebFilterIsActive returning: NO
[Google]: Log redirect url: https://socialize.eu1.gigya.com/socialize.login
[Google]: Log redirect url: https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id=910669540881-6t0ko5lh4bv1mmaavf1ebdo590tku5jj.apps.googleusercontent.com&redirect_uri=https%3a%2f%2faccounts.vrt.be%2fGS%2fGSLogin.aspx%3f&scope=email+https%3a%2f%2fwww.googleapis.com%2fauth%2fplus.login&state=yc463l70n4055151h7.np.tk1..AcbHGTofjA.n_NS81ZVGkQ6qLepg_Ufy_Ddvr37DfJpDVtVLI_5Xq4.wGOw9gYCO81_AASLiz4Zi97qnSeUshCDD_WwaOQhcUWTxgCbs4pWq3dR7kKmYaTiPNxC0m7RSjCJB8utEKcMsg.sc3
[Google]: Log redirect url: https://accounts.google.com/signin/oauth/error?authError=ChRkaXNhbGxvd2VkX3VzZXJhZ2VudBKSAUdvb2dsZSBjYW7igJl0IHNpZ24geW91IGluIHNhZmVseSBpbnNpZGUgdGhpcyBhcHAuIFlvdSBjYW4gdXNlIEdvb2dsZSBzaWduLWluIGJ5IHZpc2l0aW5nIHRoaXMgYXBw4oCZcyB3ZWJzaXRlIGluIGEgYnJvd3NlciBsaWtlIFNhZmFyaSBvciBDaHJvbWUuGlxodHRwczovL2RldmVsb3BlcnMuZ29vZ2xlYmxvZy5jb20vMjAxNi8wOC9tb2Rlcm5pemluZy1vYXV0aC1pbnRlcmFjdGlvbnMtaW4tbmF0aXZlLWFwcHMuaHRtbCCTAw%3D%3D&client_id=910669540881-6t0ko5lh4bv1mmaavf1ebdo590tku5jj.apps.googleusercontent.com
`

Thank you,
Jérémie

**Comment by sagishm** [comment]
it looks like `GoggleWrapper.swift` is missing or not attach to your project.
Go to: `Porject -> Build Phases -> Compile sources` and verify the `GoogleWrapper.swift` is included.

**Comment by jeremie-movify** [comment]
> it looks like `GoggleWrapper.swift` is missing or not attach to your project.
> Go to: `Porject -> Build Phases -> Compile sources` and verify the `GoogleWrapper.swift` is included.

Unfortunately that's not our issue; the `GoogleWrapper.swift` is already included in our project's sources.

**Comment by sagishm** [comment]
Basically from your log, our sdk not found the wrapper, you are using ReactNative or Xamarin?
Can you attach your project?

**Comment by jeremie-movify** [comment]
> Basically from your log, our sdk not found the wrapper, you are using ReactNative or Xamarin?
> Can you attach your project?

Unfortunately attaching the project is not possible. We're not using a wrapper, the `VRTLoginUI` project is the sample app of a private pod.

**Comment by sagishm** [comment]
So if you implement our SDK in ReactNative/Xamarin/private pod you need to register the wrapper ( because SDK searches the wrapper in the main project).
for example: 
`gigya?.registerSocialProvider(of: .google, wrapper: GoogleWrapper())`

if that does not resolve your issue please open an incident. (https://developers.gigya.com/display/GD/Opening+A+Support+Incident)
Thanks

**Comment by jeremie-movify** [comment]
Good afternoon,

After a deeper look into the Swift Gigya SDK's code, we found the root cause of our issue.
The GoogleWrapper was successfully registered (via `gigya?.registerSocialProvider(of: .google, wrapper: GoogleWrapper())`), but its `login` function was never called.
We found out that due to a developer error (🖐) we were using the `GigyaSocialProviders.init?(rawValue: String)` with the `Google` string, instead of `google`, thus causing the initialiser to fall back to `self = .web(provider: rawValue)`, effectively not using the `GoogleWrapper`.

To avoid this kind of mistake in the future, could I suggest modifying the initialiser from
`public init?(rawValue: String) {
        switch rawValue {
        case "facebook":`
to
`public init?(rawValue: String) {
        switch rawValue.lowercased() {
        case "facebook":` ?

Thank you for looking into this issue, please consider it closed.

Best regards,

Jérémie

**Comment by sagishm** [comment]
Basically, you can make a pull request and I will merge it in the next release.
But np, thank you for reporting.

**Comment by jeremie-movify** [comment]
@sagishm Here's the suggested PR: https://github.com/SAP/gigya-swift-sdk/pull/15
Thank you!

Jérémie
