### ISSUE TITLE
Build fails for TestApp and GigyaE2ETestsApp

### ISSUE THREAD

**Issue by MarcoEidinger** [SAP/gigya-swift-sdk#18]
Building `TestApp` or `GigyaE2ETestsApp` from `GigyaSwift.xcworkspace` is not possible because sources of non-existing folder `TestApp/GigyaProviders` are specified in 'Compile Sources' build phase

<img width="1512" alt="Screen Shot 2020-12-14 at 5 23 10 PM" src="https://user-images.githubusercontent.com/4176826/102155769-1285a480-3e31-11eb-96d4-3965d67bb290.png">

FYI: I ran `pod install` to download dependencies beforehand

**Comment by sagishm** [comment]
Hi,
The GigyaE2ETestApp is our e2e test app, the official demo app is included in the release page.
https://github.com/SAP/gigya-swift-sdk/releases/tag/core%2Fv1.1.6

Thanks
