### ISSUE TITLE
GigyaTfa package causing fatal crash

### ISSUE THREAD

**Issue by geoff-winner** [SAP/gigya-swift-sdk#19]
Hello,

We are attempting to upgrade the gigya-swift-sdk so that we can compile our app with Xcode 12+

Upgraded to Gigya pod v1.1.7 and GigyaTfa pod v1.0.10.

Building with Xcode 12.3 on an iPhone 11 using iOS v14.3.

The app is compiling with Xcode 12+ now and regular logging in without TFA interruptions appears to be working correctly.

During the interruption portion of logging in with an account that is either attempting to enable TFA or already has TFA enabled though, we are currently seeing a fatal error in TFAResolverFactory.swift. According to Xcode the error appears to be occurring on line 26 in TFAResolverFactory.swift, `return resolverA as! T`.

Here is the specific error message we are seeing,

"Could not cast value of type 'Gigya.TFAResolver<Gigya.GigyaAccount>' (0x117fb92c8) to 'GigyaTfa.RegisterPhoneResolver<Gigya.GigyaAccount>' (0x117fb90d0)."

I want to note that prior to updating the SDK the code we wrote was working and I also want to note that I reviewed the documentation provided with the gigya-tfa package and from what I can tell we are correctly using the resolverFactory code in both the `case .pendingTwoFactorRegistration(let response, let inactiveProviders, let resolverFactory):` and `case .pendingTwoFactorVerification(let response, let activeProviders, let resolverFactory):`.

Here are the examples of our code.

        // Evaluate interruption.
        switch interruption {
          // Case for enabling TFA
          case .pendingTwoFactorRegistration(let response, let inactiveProviders, let resolverFactory):
            self?.registerPhoneResolver = resolverFactory.getResolver(for: RegisterPhoneResolver.self)
            self?.sendEvent(withName: "TFAPendingRegistration", body: nil)
          // Case for existing TFA accounts logging in
          case .pendingTwoFactorVerification(let response, let activeProviders, let resolverFactory):
            self?.verificationPhoneResolver = resolverFactory.getResolver(for: RegisteredPhonesResolver.self)
            self?.verificationPhoneResolver!.getRegisteredPhones(completion: self!.registeredPhonesResult(result:))

Hoping to either get some insight into whether or not we have incorrectly used the resolver _or_ if there is a potential issue in the SDK code.

Thank you very much!

- Geoff

**Comment by sagishm** [comment]
Hi Geoff,
Thanks for reporting, are you using the last version of Xcode(12.3)?
it looks likes a fixed for the old Xcode version, I will fix it in the next version.
If you need a quick fix/workaround let me know.

Thanks,
Sagi

**Comment by geoff-winner** [comment]
Hi @sagishm,

Yes I was/am using Xcode 12.3. I was also using a much older version, 11.4. The same error occurred on both. I could try using 12.2 as well?

Building with Xcode 12.3 on an iPhone 11 using iOS v14.3.

Thanks

**Comment by sagishm** [comment]
I found the issue and i will fix it soon as possible, if you are using our CocoaPods you can using core 1.1.3 version.
I will update here when is relase.

**Comment by geoff-winner** [comment]
Great, thank you @sagishm

**Comment by sagishm** [comment]
Hi,
version with fix is released.
Thanks
