### ISSUE TITLE
Not working with Xcode 12

### ISSUE THREAD

**Issue by felexx90** [SAP/gigya-swift-sdk#2]
I'm having problems trying to make it work with Xcode 12. I get this errors

![image](https://user-images.githubusercontent.com/7705569/93556449-c23c9a80-f946-11ea-8e4f-6f74da4747fb.png)

![image](https://user-images.githubusercontent.com/7705569/93556554-ffa12800-f946-11ea-8f26-788f18805dbd.png)

**Comment by iamszabo** [comment]
Same issue here. It's easy to reproduce it in a new project just import Gigya through Cocoapods in Xcode 12 and you will receive a `Segmentation fault: 11` error while compiling Gigya.
There is a workaround if you change the Swift Compiler - Code Generation / Optimization Level to No Optimization but to make it a persistent change you need to add this to the end of your Podfile.

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'Gigya'
         config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
      end
    end
  end
end
```

The change is fine for debugging purposes, not sure about what effect would have in a Release build.

**Comment by felexx90** [comment]
@iamszabo Thanks for the help it worked

**Comment by sagishm** [comment]
there is another workaround: #3

**Comment by saurabhmshr476** [comment]
The above solution is not working in Xcode 12.4. 
Earlier Gigya binary SDK is working with Xcode 11 .
When try to run then mutliple errors came as shown in above sceenshot.
I removed binary framework and include gigya framework via cocoapods but still I'm facing issues .

I tried the @iamszabo solution provided by  . But it is not working.
Can Anyone help me.
Thanks
