### ISSUE TITLE
XCode 12.4 : Gigya Framework is not working

### ISSUE THREAD

**Issue by saurabhmshr476** [SAP/gigya-swift-sdk#21]
Earlier - XCode 11.2 , Gigya binary framework and it was working with no issue.

Now - XCode 12.4, Gigya is installed through cocoapods and it's give me 165 errors.

Example - Network error is not a member type 'Gigya'

Any  Suggestions ?

Pod Version in my project - 

Installing Alamofire (4.8.1)
Installing AlamofireImage (3.5.0)
Installing AppAuth (1.4.0)
Installing FBSDKCoreKit (5.11.1)
Installing FBSDKLoginKit (5.11.1)
Installing FBSDKShareKit (5.5.0)
Installing Firebase (6.34.0)
Installing FirebaseABTesting (4.2.0)
Installing FirebaseAnalytics (6.9.0)
Installing FirebaseCore (6.10.4)
Installing FirebaseCoreDiagnostics (1.7.0)
Installing FirebaseCrashlytics (4.6.2)
Installing FirebaseDynamicLinks (4.3.1)
Installing FirebaseInstallations (1.7.0)
Installing FirebaseRemoteConfig (4.9.1)
Installing GTMAppAuth (1.1.0)
Installing GTMSessionFetcher (1.5.0)
Installing Gigya (1.1.8)
Installing GoogleAnalytics (3.17.0)
Installing GoogleAppMeasurement (6.9.0)
Installing GoogleDataTransport (7.5.1)
Installing GoogleMaps (3.9.0)
Installing GooglePlaces (3.9.0)
Installing GoogleSignIn (5.0.2)
Installing GoogleSymbolUtilities (1.1.2)
Installing GoogleTagManager (7.1.4)
Installing GoogleUtilities (6.7.2)
Installing GoogleUtilitiesLegacy (1.3.2)
Installing MarketingCloudSDK (7.1.1)
Installing PromisesObjC (1.2.12)
Installing SkyFloatingLabelTextField (3.6.0)
Installing SwiftKeychainWrapper (3.4.0)
Installing SwiftTheme (0.4.3)
Installing nanopb (1.30906.0)

Thanks

**Comment by sagishm** [comment]
Hi,
It looks like you still have the old `Gigya.framework`, please make sure you removed all references of `Gigya.framework`.

Thanks
