### ISSUE TITLE
Crash at start for app not launching

### ISSUE THREAD

**Issue by aruffolo** [SAP/gigya-swift-sdk#22]
Hi

Sometimes it happens that the app won't start and will be terminated by the system after the 10 secs timeout
Looking at the logs I've found that the top thread is executing code from Gigya

[crash_start.log](https://github.com/SAP/gigya-swift-sdk/files/5966015/crash_start.log)

 I don't know if the SDK is really the issue, could you take a look?
 
 Thanks

**Comment by sagishm** [comment]
Hi,
it does not look like SDK issue, can you reproduce it?
Can you add logs from Console tab?
Thanks

**Comment by aruffolo** [comment]
Hi sorry for the late answer,

It's not easy to reproduce it but I'll make some runs.
I'll enable the Gigya debug log flag and come back as soon as I have something
