### ISSUE TITLE
iOS Framework Build Script deletes required libraries

### ISSUE THREAD

**Issue by pflugs30** [SAP/gigya-swift-sdk#23]
The `ios-framework-build.sh` script has a bug.  Its job is to remove unneeded Gigya libraries from the Xcode build, but it also accidentally removes our own required libraries.  Without a fix, we are not be able to build our own releases without manually modifying the build script which is not possible with Swift Package Manager.

I've included a corrected version of this script for you to use.  Would it be possible to replace the script soon?  Thanks.
```sh
APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"

# This script loops through the frameworks embedded in the application and

# removes unused architectures.
find "$APP_PATH" -name '*.framework' -type d | grep $1 | while read -r FRAMEWORK
do
FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"

EXTRACTED_ARCHS=()

for ARCH in $ARCHS
do
echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
done

echo "Merging extracted architectures: ${ARCHS}"
lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"
rm "${EXTRACTED_ARCHS[@]}"

echo "Replacing original executable with thinned version"
rm "$FRAMEWORK_EXECUTABLE_PATH"
mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"

done
```

**Comment by sagishm** [comment]
We will check it in the next release.
Also, Remove architectures script is not needed with Swift Package Manager.

Thanks

**Comment by pflugs30** [comment]
@sagishm Now that [Issue 24](https://github.com/SAP/gigya-swift-sdk/issues/24) is closed, can this issue be reopened and resolved?  Thanks!
