### ISSUE TITLE
Add tags for package releases

### ISSUE THREAD

**Issue by pflugs30** [SAP/gigya-swift-sdk#24]
It’s great that you guys now support Swift Package Manager.  This is our preferred integration method.

I used the SPM option, and my build worked.  However, I was only able to create a dependency on the “master” branch.  I would prefer to make a dependency on a tagged release branch for the packages, similar to [the tags](https://github.com/SAP/gigya-swift-sdk/tags) that already exist.

Can you please create a tag for the packages so we can point to specific releases in our builds?  Hopefully, this change can be made without too much impact to your processes.  Thank you.

**Comment by sagishm** [comment]
Currently, Swift Package Manager has only supported the latest version.

**Comment by sprout-apps** [comment]
I believe Swift Package Manager does support tagging: https://developer.apple.com/documentation/xcode/publishing_a_swift_package_with_xcode.

"It’s a best practice to create a version tag for a Swift package; however, there are other ways to add a package to a project, as described in Adding Package Dependencies to Your App. To create a version tag, tag the last commit with the package version. A package version is a three period-separated integer. An example is 1.0.0. The package version must conform to semantic versioning to ensure that your package behaves in a predictable manner when developers update their package dependency to a newer version.
To learn more about the semantic versioning standard, visit semver.org."

**Comment by sagishm** [comment]
Of course Swift Package Manager is supported tagging but because we have few frameworks in one repo that’s make it harder, so at this time it is not on our roadmap.

**Comment by pflugs30** [comment]
@sagishm As a fellow developer, I understand the challenges with having everything in one repository.  The trouble for us is that we want to rely on a specific version of a specific package.  If we don't, then a future build of your packages may include a breaking change to our app.  I'm sure you can understand our position.

I know the difficulty in refactoring an entire repository.  In the meantime, can you create a separate repository for the compiled packages and publish to SPM from there?  That would be a balance between our requirements.

If you have another solution, we would appreciate hearing it.  Thank you.

**Comment by sagishm** [comment]
Hi All,
From 1.2.0 all versions will tags. (currently, 1.2.0 got a tag for SPM)

**Comment by pflugs30** [comment]
@sagishm Thank you for letting us know.  We look forward to incorporating this capability into our next release.
