### ISSUE TITLE
Duplicate nonce

### ISSUE THREAD

**Issue by ghena** [SAP/gigya-swift-sdk#26]
Dear sirs,

using a testflight version gigya local account in PROD return me always a Duplicate nonce.

403004 errorCode.

It doesn't happens when i try with IOS simulator,

Could you give more information how to resolve this ?

Regards.
g.

**Comment by sagishm** [comment]
Hi, Please open a support case using https://developers.gigya.com/display/GD/Opening+A+Support+Incident and provide all the relevant data.
Thanks
