### ISSUE TITLE
Xcode 12.4 non fat binary (XCFramework) version of the framework

### ISSUE THREAD

**Issue by jeksys** [SAP/gigya-swift-sdk#28]
Can you please release non fat binary version (XCFramework format) of the framework to support Xcode >12.4. To get rid of the following error:

Building for iOS Simulator, but the linked and embedded framework 'Gigya.framework' was built for iOS + iOS Simulator.

**Comment by sagishm** [comment]
Hi jeksys,
The XCFramework package is on our roadmap, at this time you can use the remove arch script.

Thanks,
Sagi

**Comment by jeksys** [comment]
@sagishm What's remove arch script? 
Can you please share it?

**Comment by sagishm** [comment]
Hi,
Can you try this please:
Go to Project -> Build settings -> search `Validate Workspace` -> switch to YES.
let me know if it works.
Thanks
