### ISSUE TITLE
Gigya Framework: Segmentation fault: 11 (in target 'Gigya' from project 'Pods') with Xcode 12.4

### ISSUE THREAD

**Issue by BhagyashreeMahajan** [SAP/gigya-swift-sdk#30]
When updated Xcode version from 11.5 to 12.4 getting below errors:
<unknown>:0: error: unable to execute command: Segmentation fault: 11
<unknown>:0: error: compile command failed due to signal 11 (use -v to see invocation)

I have tried to run the code on simulator and it's working but not able to archive.

**Comment by sagishm** [comment]
Hi, Please open a support case using https://developers.gigya.com/display/GD/Opening+A+Support+Incident and provide all the relevant data.
Thanks
