### ISSUE TITLE
Xcode 12.2 Error, Apple M1 : Module 'Gigya' was created for incompatible target arm64-apple-ios10.0:

### ISSUE THREAD

**Issue by jeksys** [SAP/gigya-swift-sdk#32]
Hardware: MacBook Pro (13-inch, M1, 2020)
Xcode Version 12.2 (12B45b)

Have an error: 'Module 'Gigya' was created for incompatible target arm64-apple-ios10.0:' building project with Gigya SDK Core/1.2.0 using Xcode 12.2 on Apple M1 Mac

Note: Cannot use Core/1.2.1 with Xcode 12.5 on M1 as the format of the library is not compatible with Xcode 12.5

**Comment by sagishm** [comment]
Hi,
Can you show me the error with Xcode 12.5, please? ( screenshot / logs)

Thanks

**Comment by jeksys** [comment]
<img width="696" alt="Screen Shot 2021-05-19 at 12 37 26 PM" src="https://user-images.githubusercontent.com/699627/118873866-19608980-b89f-11eb-9391-cc666c4ced07.png">

**Comment by jeksys** [comment]
<img width="866" alt="Screen Shot 2021-05-19 at 12 39 13 PM" src="https://user-images.githubusercontent.com/699627/118874066-5593ea00-b89f-11eb-886c-e7e82a9c0045.png">

**Comment by jeksys** [comment]
I guess it's because the min target for Gigya target is 10.0

Also if you can create xcframework version of the library it will help us to move to Xcode 12.5

**Comment by jeksys** [comment]
Xcode Version 12.5 (12E262) error

<img width="540" alt="Screen Shot 2021-05-19 at 12 45 22 PM" src="https://user-images.githubusercontent.com/699627/118874794-2336bc80-b8a0-11eb-91cf-7fe07742e2ef.png">

**Comment by sagishm** [comment]
Hi,
Go to Project -> Buils settings -> search ‘validate workspace’ and change it to ‘YES’.
Let me know if it helps.
Thanks

**Comment by jeksys** [comment]
No, it didn't help

**Comment by sagishm** [comment]
In Xcode 12.5 and Gigya 1.2.1 it should be works, if not please open case:
https://developers.gigya.com/display/GD/Opening+A+Support+Incident

i need more details to investigate the issue.
Thanks

**Comment by jeksys** [comment]
Do you have access to Apple M1? 

Gigya 1.2.0 finally worked for me on M1 with Xcode 12.2 in the Rosetta mode 

<img width="236" alt="Screen Shot 2021-05-19 at 12 57 54 PM" src="https://user-images.githubusercontent.com/699627/118876220-d9e76c80-b8a1-11eb-93e6-44623a66497a.png">

**Comment by jeksys** [comment]
@sagishm do you have any plans to release xcframework version of Gigya framework?

**Comment by jeksys** [comment]
Have you tested Gigya framework 1.2.1 using Xcode 12.5 on Apple M1 or just a regular Intel MacBook?

**Comment by sagishm** [comment]
Only on intel mac, i had the same issue with Xcode 12.5 but the validate workspace was fixed it.
Another question, why you wouldn’t used SPM or CocoaPods? There is specific reason?
Thanks

**Comment by jeksys** [comment]
>Another question, why you wouldn’t used SPM or CocoaPods? There is specific reason?
We use Carthage. But I had issues pulling  and building Gigya using it, not sure if it is Gigya or Carthage specific. So sendup using released framework instead

**Comment by sagishm** [comment]
> > Another question, why you wouldn’t used SPM or CocoaPods? There is specific reason?
> 
> We use Carthage. But I had issues pulling and building Gigya using it, not sure if it is Gigya or Carthage specific. So sendup using released framework instead

I working on solution for Carthage, send me email and i will update you when is ready.

sagi.shmuel@sap.com
