### ISSUE TITLE
Not taking the "startScreen" parameter into account

### ISSUE THREAD

**Issue by Dooks123** [SAP/gigya-swift-sdk#34]
I am trying to display a web screenSet with a specific `startScreen` in iOS but it does not work.

Looking at this file:
https://github.com/SAP/gigya-swift-sdk/blob/main/GigyaSwift/Global/Plugins/PluginViewWrapper.swift

It does pass the parameters in this script tag:
https://github.com/SAP/gigya-swift-sdk/blob/6de016ae29a576844d7d39526c50269782e40c8b/GigyaSwift/Global/Plugins/PluginViewWrapper.swift#L138-L143

But it doesn't show the `startScreen` I provide, it shows the default `giga-login-screen`.

I am using this SDK via a flutter plugin:
#https://github.com/SAP/gigya-flutter-plugin/issues/16#issue-988955132

On Android it shows the correct `startScreen` but not in iOS.

The flutter plugin passes in the correct parameters to the Swift SDK but the SDK does nothing with the information.

**Comment by Dooks123** [comment]
We have added an anchor on the HTML:

    <a href="#" data-switch-screen="MobileLogin">Switch</a>

And this shows the correct screen. Can this issue please be sorted out?

**Comment by sagishm** [comment]
This bug is related to `flutter` plugin and will resolve in the next release.
