### ISSUE TITLE
Xcode 13 RC transparent navigation bar for screensets

### ISSUE THREAD

**Issue by g-enius** [SAP/gigya-swift-sdk#35]
After upgrading to Xcode 13 (beta & RC), the navigation bar of the screensets change to transparent.
See the screenshot attached. It only happens when building the project from Xcode 13 and run it on iOS 15 simulators/devices.

We can't manipulate it from client-side as all we do is calling the API `Gigya.sharedInstance().showScreenSet`.

![simulator_screenshot_291A0026-3D16-496B-8462-B9D484408925](https://user-images.githubusercontent.com/16376917/133358195-ea1e65dd-530f-41f3-98cc-8fea8490e8a3.png)

**Comment by marcoreni** [comment]
@g-enius  we are encountering the same issue. Did you manage to solve it? Can you explain how?
