### ISSUE TITLE
Gigya framework incompatible with Xcode 13

### ISSUE THREAD

**Issue by badlands** [SAP/gigya-swift-sdk#36]
Please update the framework for use with Xcode 13

**Comment by sagishm** [comment]
Basically, we are not supporting `framework` anymore and we are forward to `xcframework` and this should be working with Xcode 13, you can download the last `xcframework` from the releases section: 
https://github.com/SAP/gigya-swift-sdk/releases/tag/core%2Fv1.2.3

let me know if you have any other issues with Xcode 13.
Thanks
