### ISSUE TITLE
TestApp missing?

### ISSUE THREAD

**Issue by potzkovge** [SAP/gigya-swift-sdk#40]
The TestApp was removed with https://github.com/SAP/gigya-swift-sdk/commit/1db359e4a44f66846ed744e5b131477cf40624bc and i cannot seem to find the new iOS Demo app.

Please help :)

**Comment by sagishm** [comment]
Hi,
TestApp is internal testing app, you can find Demo app there: https://github.com/SAP/gigya-swift-sdk/releases/tag/core%2Fv1.2.1
just run `pod update`/`pod install`.
Thanks,
Sagi
