### ISSUE TITLE
iOS GoogleSignIn 

### ISSUE THREAD

**Issue by andrejicmilos93** [SAP/gigya-swift-sdk#43]
Hi, I'm having problem signing in with Google. 

I have everything setup, but my iOS Credential is not inside 'Google Configuration' on Gigya Console, since it can only have one 'Consumer Key' which is the Web one. Because of that, I get  "invalid_audience: Audience is not a valid client ID" when I try to login with my iOS Credential(clientID and reversedID set as allowed URL). 

What am I doing wrong? How can I solve this problem?
Is there a way to add an iOS Credential to 'Google Configuration' on Gigya Console?

Just to mention, Facebook is working fine.

Please let me know if I can provide any more info on this.

**Comment by sagishm** [comment]
Hi,
Basically in Gigya Console the configuration need to be like the web.
you error meant you didn't configure properly the Google iOS SDK.
Please follow the instruction from Google: https://developers.google.com/identity/sign-in/ios/start-integrating
Once you done with that follow our instruction: https://github.com/SAP/gigya-swift-sdk/tree/main/GigyaSwift#google (Don't forget the `GoogleWrapper.swift` file)

Thanks,
Sagi

**Comment by andrejicmilos93** [comment]
Thanks, all I needed was the confirmation that Console configuration is set with web credentials.
