### ISSUE TITLE
GigyaProviders not visible

### ISSUE THREAD

**Issue by mfentross** [SAP/gigya-swift-sdk#44]
In the documentation you frequently refer the the GigyaProviders directory that e.g. contains the GoogleWrapper.swift file. However this is nowhere included. [You can find the documentation I am talking about here.](https://sap.github.io/gigya-swift-sdk/GigyaSwift/#google)

**Comment by siegeral** [comment]
The `GigyaProviders.zip` is included in the Assets with each release (tap on "Assets" will reveal the content)
https://github.com/SAP/gigya-swift-sdk/releases

The latest:
https://github.com/SAP/gigya-swift-sdk/releases/tag/core%2Fv1.3.1

**Comment by mfentross** [comment]
Thank you :)
