### ISSUE TITLE
Merge conflicts present in .gitignore

### ISSUE THREAD

**Issue by bitcrumb** [SAP/gigya-swift-sdk#45]
Hi, I noticed that merge conflicts are present in the .gitignore file of this repo.

I guess these better be resolved?

https://github.com/SAP/gigya-swift-sdk/blob/main/.gitignore

**Comment by sagishm** [comment]
it's just .gitignore ,you don't need to care about that but i will check that.

**Comment by bitcrumb** [comment]
I perfectly know what a .gitignore is, it’s just better not to have it in a conflicting state… right? :-)
