### ISSUE TITLE
Custom Button in Login Screenset is not showing

### ISSUE THREAD

**Issue by Aaron98990** [SAP/gigya-swift-sdk#46]
In the screenset, we are able to get the screenset to show up but it is missing the SSO button implemented as shown in the image below. We are able to get this to work on the WebSDK version  but we are missing the custom button in ios SDK. Do you have any ideas?

`public func showScreenSet(with name: String, viewController: UIViewController, params: [String: Any] = [:], completion: @escaping (GigyaPluginEvent<T>) -> Void)`
 
`let params = ["screenSet": "SCREENSETNAME", "idpName": "IDPNAME", "type": "saml", "position": "1", "deviceType": "mobile",  "providerName": "PROVIDER NAME", "startScreen": "SCREENNAME", "containerID": "pluginContainer"]`

Mobile SDK:

<img width="368" alt="image" src="https://user-images.githubusercontent.com/45950113/175061961-bb1ca541-e9e3-467d-995c-0e04674cee1f.png">

For reference, this is how it is done in web sdk which works and shows the custom button and the screenset correctly:

```
gigya.accounts.showScreenSet({
  containerID:'login',
  screenSet: 'fill in',
  startScreen: 'fill in',
  customButtons: [{
  'type': 'saml',
  'providerName': 'fill in',
  'idpName': 'fill in',
  'lastLoginIconURL': 'URL',
  'position': '1'}],
  });
```

**Comment by sagishm** [comment]
Hi, Please open a support case using https://developers.gigya.com/display/GD/Opening+A+Support+Incident and provide all the relevant data and crash reports in order for our team to investigate this issue.

**Comment by Aaron98990** [comment]
Thank you! This resolved our issue.

### Custom Buttons:

Custom Buttons work using the Swift SDK. But, the `params` must be formated like this in the Swift `showScreenSet` call.

`["screenSet": "",  "startScreen": "", "deviceType": "", "containerID": "", "customButtons": [{"idpName": "", "providerName": "", "type": "saml", "position": "1"}]`

### Add these sites to the Trusted URLs:
- `gsapi://*`
- For Objective-C, enter both `gsapi://*` and the bundle ID of your project (e.g., `com.app.app://*`).
