### ISSUE TITLE
 Duplicate nonce errors from Gigya.login after password reset

### ISSUE THREAD

**Issue by HDBAGORIAR** [SAP/gigya-swift-sdk#47]
`Error: ["callId": 6e37d8e0aa4a4a8c827c6db252bed19e, "time": 2022-06-28T07:29:56.923Z, "statusReason": Forbidden, "statusCode": 403, "apiVersion": 2, "errorDetails": Duplicate nonce, "errorCode": 403004, "errorMessage": Duplicate nonce]`

**I experience the issue in latest gigya ios sdk.**

This issue arise after the user reset the password. And even after launching the application again we are getting the same error until we delete the application and reinstall the new one.

`gigya.initFor(apiKey: xxxx, apiDomain: yyyy)` is called every time user launches the application, to initiate the gigya sdk. So, even if the user relaunches the application the error is same.

`If after password reset success call, we call gigya logout then the issue does not arise. But iam still unclear if no session is created during the reset process OR we need to proceed in this way`

Please let us know the fixes.

**Comment by MarlonAEC** [comment]
Are there any updates on this? a big chunk of our users are facing this issue and we have a ton of logs regarding this issue in both platforms IOS and Android, reviews are coming after us as usual, is this issue being tackled or is there any coming fix for it? Do we have to do something on our side? I really appreciate any help you can provide!

**Comment by MarlonAEC** [comment]
Hello @sagishm, I noticed you closed this issue, is there an update? Our clients are still getting this issue and we are waiting for an update to fix it. Do you guys have a new release that solves this issue? Or is there something we have to do to fix this issue? I really appreciate any help you can provide.

**Comment by sagishm** [comment]
hi,
i closed because it's looks like server issue and not related to sdk.
if you still have that issue, please open incident and not github issue.

https://developers.gigya.com/display/GD/Opening+A+Support+Incident
thanks
