### ISSUE TITLE
Integrate swift core SDK in Objective c project error

### ISSUE THREAD

**Issue by fcmeca** [SAP/gigya-swift-sdk#49]
I have an old Objc project and I want to integrate the swift sdk, when I add the pod and try to import it in the AppDelegate.m can't call [Gigya sharedInstace]; because it is not found .... is integration possible?
 If so, can you tell me where I can find an integration guide for an Objc project?
Thanks.

**Comment by sagishm** [comment]
You need to create bridge between Objc to Swift class and implement the instruction in your swift bridge.
