### ISSUE TITLE
Gigya framework does not work with XCode12.

### ISSUE THREAD

**Issue by RichP** [SAP/gigya-swift-sdk#5]
When building projects linked against the latest Gigya framework using Xcode 12 we experience 184 compilation errors.  The root cause stems from:

"Failed to build module 'Gigya' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)'"

**Comment by sagishm** [comment]
upgrade to the last version please.
