### ISSUE TITLE
Error while archiving with SPM integration

### ISSUE THREAD

**Issue by JosueQuinonesRivera** [SAP/gigya-swift-sdk#52]
I integrated Gigya SDK using SPM and it is working locally. However, when I try to archive my project, I am receiving an error saying that `no such module 'CryptoKit'` in all the files that is being used.

**Comment by sagishm** [comment]
Hello,
After checking everything works here.
if you still have it just add the `CryptoKit` in your Project -> General -> Frameworks, Libraries and Embedded Content.
Thanks
