### ISSUE TITLE
Screen set webviews never discard, kept in memory forever

### ISSUE THREAD

**Issue by bitcrumb** [SAP/gigya-swift-sdk#53]
While debugging some webview issues when presenting web screensets, I noticed (through Safari developer tools) that none of the webviews seem to get removed from memory.

The list of webviews just keeps building up whenever I open & close web screensets consecutively.

I would expect each instance to be discarded when a user cancels or finishes the flow. This is most probably a retain issue with either view controllers or the webviews itself.

NOTE: I am actually using the react-native SDK, but I assume this is a native issue.

![Screenshot 2023-01-18 at 21 49 02](https://user-images.githubusercontent.com/135126/213292029-1635a8a3-5e82-4c36-b5a1-d1eb636f3c21.png)

**Comment by sagishm** [comment]
thanks for report, bug opened and we will fix soon as possible.

**Comment by sagishm** [comment]
fixed
