### ISSUE TITLE
Demo App Files Missing

### ISSUE THREAD

**Issue by Yurssoft** [SAP/gigya-swift-sdk#55]
I have tried to run example apps that go with project. Seems like they missing. Is this possible to include them please? 

<img width="248" alt="Screenshot 2023-02-24 at 11 21 35" src="https://user-images.githubusercontent.com/7051552/221269797-26d44e48-120d-4656-9d60-cadc11260fb7.png">

**Comment by sagishm** [comment]
Hi,
demo app is available to download there: https://github.com/SAP/gigya-swift-sdk/releases/download/core%2Fv1.2.1/CdcDemoApp.zip

you can download and run 'pod update'.
