### ISSUE TITLE
In gigya core class, some methods are protected level, would you please make them to public?

### ISSUE THREAD

**Issue by ajunjunandtmac** [SAP/gigya-swift-sdk#57]
1.   func isAvailable(loginId: String, completion: @escaping (GigyaApiResult<Bool>) -> Void)
2.  func verifyLogin(UID: String, params: [String: Any] = [:], completion: @escaping (GigyaApiResult<T>) -> Void) 
Thanks very much

**Comment by sagishm** [comment]
fixed
