### ISSUE TITLE
Where is FacebookWrapper.swift

### ISSUE THREAD

**Issue by ksmaxeed** [SAP/gigya-swift-sdk#6]
Hi, I'm developing iOS app with gigya-swift-sdk and Facebook Login.
My application has error when facebook login.
I think the reason berow,
[https://developers.gigya.com/display/GD/Swift+SDK#SwiftSDK-Facebook](https://developers.gigya.com/display/GD/Swift+SDK#SwiftSDK-Facebook)
```you need to import "FacebookWrapper.swift" file from "GigyaProviders" dictionary to your Xcode project.```
But I can not find "FacebookWrapper.swift" in this repository.

I find FacebookWrapper.swift in commit "98de0cd"(2019/4/30).
Why the file has deleted?
and Where can I copy the file from now?
(also GoogleWrapper.swift)

**Comment by jeremie-movify** [comment]
@ksmaxeed Good morning,

The `GigyaProviders` indeed seem to be missing from the repo as of version 1.1. In the meantime, you can find the native login wrappers at https://downloads.gigya.com/predownload?fileName=Swift-Core-framework-1.0.9.zip

Best regards,

Jérémie

**Comment by sagishm** [comment]
Hi @ksmaxeed,

Also, you can download it from the `Release` section.

Here is the link: https://github.com/SAP/gigya-swift-sdk/releases/tag/core%2Fv1.1.4

Sagi.

**Comment by sagishm** [comment]
ok will do it, thanks for the proposal, regard Facebook SDK, version 7.x is compatible and we have in the roadmap to test version 8.
