### ISSUE TITLE
Cannot login with Line

### ISSUE THREAD

**Issue by phuoclinh** [SAP/gigya-swift-sdk#61]
I get the wrapper from the [link](https://github.com/SAP/gigya-swift-sdk/releases/download/core%2Fv1.5.3/GigyaProviders.zip)
Has callback with dictionary contains `accessToken` and `uid` in wrapper class
But the response of API: https://accounts.au1.gigya.com/accounts.notifySocialLogin is
{
	"callId": "7a785a38584e4ee9ab51a29b834fedde",
	"errorCode": 500002,
	"errorMessage": "Server login error",
	"apiVersion": 2,
	"statusCode": 500,
	"statusReason": "Internal Server Error",
	"time": "2023-06-08T08:03:39.147Z",
	"errorDetails": "500002 - Server login error"
}

could you please check it?
thanks

**Comment by sagishm** [comment]
Hello,
it's looks like implementation issue, please open incident in SAP system.

https://developers.gigya.com/display/GD/Opening+A+Support+Incident
Thanks,
Sagi
