### ISSUE TITLE
Swift Compiler Error (Xcode): Value of type 'WKWebView' has no member 'isInspectable'

### ISSUE THREAD

**Issue by karim-8** [SAP/gigya-swift-sdk#67]
I had this issue and causing an Error in flutter build in the pipeline as the latest updated in your version in core can you please check

Swift Compiler Error (Xcode): Value of type 'WKWebView' has no member 'isInspectable'
/Users/runner/work/1/s/ios/Pods/Gigya/GigyaSwift/Global/Plugins/GigyaWebBridge.swift:88:26

**Comment by sagishm** [comment]
update your xcode to last release.

**Comment by karim-8** [comment]
Hello @sagishm I have fixed this issue by assigning the pod file to a previous version, I think they need to make the property with default value or to do it in a different way that does not impact the previous versions.

  pod 'Gigya', '1.5.4'
  
  Hopefully, this can help anyone in need.
