### ISSUE TITLE
@objc annotations needed for Xamarin bindings

### ISSUE THREAD

**Issue by mauro3005** [SAP/gigya-swift-sdk#7]
The swift project does not have @objc annotations to expose the code to being binded to c# projects such as mobile app projects in Xamarin.

Classes and methods needed for SDK use needs to have @objc and also be public modifier.

Is this possible to update? That would make using in Xamarin projects straightforward using objective sharpie to create a bindable framework.

**Comment by sagishm** [comment]
Hi, we will look into it in future updates.
If this is a priority for you, you are able to open a support ticket.

https://developers.gigya.com/display/GD/Opening+A+Support+Incident
