### ISSUE TITLE
Missing Privacy Manifest File PrivacyInfo.xcprivacy

### ISSUE THREAD

**Issue by cathalfarrell** [SAP/gigya-swift-sdk#78]
### Checklist

- [X] The issue can be reproduced in the attached sample application in the repository.
- [X] I have read the relevant [SDK documentation](https://github.com/SAP/gigya-swift-sdk#sap-cdc-gigya-swift-sdk) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [SAP Code of Conduct](https://github.com/SAP/gigya-swift-sdk/blob/main/CODE_OF_CONDUCT.md).

### Description

1. Apple requires all apps and SDKs to provide a PrivacyInfo.xcprivacy file from Spring 2024 as per documentation:
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files?language=objc

2. Expected
I expect to find a file called PrivacyInfo.xcprivacy bundled in the SDK

3. Actual
The PrivacyInfo.xcprivacy is missing from the SDK

### Reproduction

1. Step 1 look for PrivacyInfo.xcprivacy inside SDK bundle and you will see that it is missing.

### SDK version

1.5.10

**Comment by sagishm** [comment]
fixed in v1.6.0
