### ISSUE TITLE
Social Login without third party SDK

### ISSUE THREAD

**Issue by kernandreas** [SAP/gigya-swift-sdk#8]
Hello.

We are currently adding user login to our app.

As we plan to add social login with Facebook we discovered in the documentation that this requires integrating the Facebook SDK into our application. We want to avoid this by implementing the authentication flow with system technologies as ASWebAuthenticationSession on iOS and Chrome Tabs on Android. As a result, our app will get the access token for this social login provider. My question to you: Are we able to pass this access token to the Gigya SDK to create a valid Gigya Account?

I did already took a deeper look at the Swift SDK Reference but did not find anything that answered this question.

Thank you.

Greetings,
Andreas Kern.

**Comment by sagishm** [comment]
Hi,
You can find it on the release page.
https://github.com/SAP/gigya-swift-sdk/releases/tag/core%2Fv1.1.5
Just download the `GigyaCore.V1.1.5.zip` and you will get it.

Thanks
