### ISSUE TITLE
How to change an active email to another but keep the same UID for a registered account?

### ISSUE THREAD

**Issue by ajunjunandtmac** [SAP/gigya-swift-sdk#80]
### Checklist

- [X] I have read the relevant [SDK documentation](https://github.com/SAP/gigya-swift-sdk#sap-cdc-gigya-swift-sdk) and have not found a suitable solution.
- [X] I agree to the terms within the [SAP Code of Conduct](https://github.com/SAP/gigya-swift-sdk/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved.

I can't find any API like changeEmail or updateEmail to change an registered email to another in the SDK
I found a similar question here https://stackoverflow.com/questions/49257874/gigya-change-email-address-when-user-name#/
It's not clear enough, can you tell me the right way how to do that?
Thanks a lot

### Describe the ideal solution.

Nothing

**Comment by sagishm** [comment]
this should be works:
https://stackoverflow.com/questions/49257874/gigya-change-email-address-when-user-name
