### ISSUE TITLE
Support for Limited Login via Facebook SDK

### ISSUE THREAD

**Issue by andrejpavlovic** [SAP/gigya-swift-sdk#83]
### Checklist

- [X] The issue can be reproduced in the attached sample application in the repository.
- [X] I have read the relevant [SDK documentation](https://github.com/SAP/gigya-swift-sdk#sap-cdc-gigya-swift-sdk) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [SAP Code of Conduct](https://github.com/SAP/gigya-swift-sdk/blob/main/CODE_OF_CONDUCT.md).

### Description

Facebook has introduced a new way to authenticate users that no longer gives access to "access tokens" in order to satisfy new iOS Privacy Manifest guidelines as per:
https://developers.facebook.com/blog/post/2024/05/09/fb-login-sdk-update
https://developers.facebook.com/docs/ios/

This means that when trying to integrate Gigya Swift SDK, we no longer are able to get the access token on successful login, but instead get an authentication token.

My question is, how can we forward this to `notifySocialLogin` which seems to only accept access tokens right now.

Does/can Gigya validate authentication tokens instead as per: https://developers.facebook.com/docs/facebook-login/limited-login/token/validating

I'll open a support request as well, but currently there doesn't seem to be support for validating Limited Login tokens.

### Reproduction

1. Configure Limited Login Facebook authentication as per https://developers.facebook.com/docs/facebook-login/limited-login/ios using [Facebook SDK v17.0.0](https://github.com/facebook/facebook-ios-sdk)
2. Login and try to pass authentication token in the same way as the access token to Gigya's `accounts.notifySocialLogin` endpoint
3. Get a 500 server error.

### SDK version

1.6.0

**Comment by sagishm** [comment]
Hi,
Please update to last version (1.6.3) also it requires to update the ‘FacebookWrapper.swift’.
Facebook limited login supports from v1.6.1.
Thanks
