### ISSUE TITLE
Facebook SDK v17 provider wrapper issue

### ISSUE THREAD

**Issue by erickok** [SAP/gigya-swift-sdk#86]
### Checklist

- [X] The issue can be reproduced in the attached sample application in the repository.
- [X] I have read the relevant [SDK documentation](https://github.com/SAP/gigya-swift-sdk#sap-cdc-gigya-swift-sdk) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [SAP Code of Conduct](https://github.com/SAP/gigya-swift-sdk/blob/main/CODE_OF_CONDUCT.md).

### Description

When we perform Facebook login using the FB SDK and your FacebookWrapper (updated for Gigya 1.7.0) the login eventually fails. It seems that in the `FacebookWrapper` your are trying to pass the expiration date back to your Gogya json:

```swift
Int32(result?.token?.expirationDate.timeIntervalSince1970 ?? 0)
```

However, I am receiving expiration dates for the year 4001, which means the `timeIntervalSince1970` is too large to fit in an Int32. Moreover, even as Int64 it does not work. If I instead modify the code to not supply any expiration date, it all works again.

```swift
let jsonData: [String: Any] = ["accessToken": result?.token?.tokenString ?? "", "tokenExpiration": result?.token?.expirationDate.timeIntervalSince1970 ?? 0]
```

### Reproduction

Just set up any project with Gigya 1.7.0, the Facebook SDK v17 and FacebookWrapper.swift taken from the [GigyaProviders-1.7.0.zip](https://github.com/SAP/gigya-swift-sdk/releases/tag/core%2Fv1.7.0) and try to sign in.

Potentially this only impacts FB apps that are still in 'App Mode: Development' - I haven't yet been able to compare this to a 'Live' app, but it should work in any case.

### SDK version

1.7.0

**Comment by sagishm** [comment]
hi
our server are not support timestamp as Int64, so if you try to login with Facebook limited login you will get an error.
please use the attached warpper.

i will update the wrapper zip too.
[FacebookWrapper.swift.zip](https://github.com/user-attachments/files/16544130/FacebookWrapper.swift.zip)

**Comment by erickok** [comment]
Thanks for the quick response. Indeed capping the expiration date to Int32.max works too.

**Comment by sagishm** [comment]
better to use this solution because when its on Facebook limited login you will get expiration that not supported by the servers.

**Comment by ajunjunandtmac** [comment]
Would you please also provide a GoogleWrapper? after i updated to core/v1.7.0, i found that google sign in can not  be used any longer.
I noticed your release note, `Note: It is required to update your provider files for this & future versions.`, but i don't know how to update it, i would be appreciate if can get some suggestion from your side
Thanks very much

**Comment by erickok** [comment]
@ajunjunandtmac you can find them in [the releases on GitHub](https://github.com/SAP/gigya-swift-sdk/releases/tag/core%2Fv1.7.0)
