### ISSUE TITLE
completion block called twice

### ISSUE THREAD

**Issue by fedegasp** [SAP/gigya-swift-sdk#9]
Hi,
 the completion block of 

public func login(with provider: GigyaSocialProviders, viewController: UIViewController,
                      params: [String: Any] = [:], completion: @escaping (GigyaLoginResult<T>) -> Void)

could be called twice.
This is due to start() method called in init() of PendingRegistrationResolver and at line 48 of InterruptionResolverFactory.swift.

**Comment by sagishm** [comment]
The bug is fixed in the 1.1.6 version.
